// Verdix commercial decision trace (Step 8) — observability/audit
// architecture only. Explains HOW a commercial field reached its current
// state by composing, unmodified, every layer already built in Steps 2-7:
// AI guidance selection (ai-guidance.ts), Global Rulebook shadow validation
// (resolver.ts), Global Rulebook invariant enforcement (activation.ts),
// Organization Rulebook matching/precedence (organization-rules.ts,
// organization-rulebook-shadow.ts), and the canonical readiness gate
// (lib/commercial-rule-status.ts's isProvenanceResolved). This module adds
// NO new resolution logic, NO new precedence, NO new provenance value, and
// writes nothing — it is a pure, read-only lens over what those layers
// already compute.
//
// Deliberately field-agnostic: buildCommercialDecisionTrace takes a plain
// field/value/provenance triple plus the same inputs Step 4/5A/5B/7 already
// consume, so a future field can reuse it directly. The one field-specific
// entry point built so far — buildServiceCreditSurvivalCarryForwardTrace,
// lib/rulebook/decision-trace-service-credit.ts — is a thin adapter on top
// of this, not a special case baked into the generic composer.
//
// Trace facts, not reasoning prose (item 2): every field here is a rule id,
// a version number, an authority/method enum value, a boolean, or a small
// structured value already flowing through the existing pure layers above
// (RulebookFinding.reason strings are template-generated by lib/rulebook/
// rules.ts, never raw contract text or model chain-of-thought — see that
// file's own evaluate() bodies). Nothing in this module's INPUT surface
// accepts a full RuleProposal, a source clause, a prompt, or an
// organization rule's name/description — see decision-trace-service-credit
// .ts's own input shape for how that's enforced structurally, not just by
// convention.
//
// Reconstructed snapshot, not historical record (Step 8 amendment) — this
// module answers "why is this field CURRENTLY resolved this way," not "why
// did Verdix ORIGINALLY decide this." A trace is always computed live, from
// today's persisted commercial state plus whatever Rulebook/Organization
// Rulebook/AI-guidance behavior the running code and organization_rulebook_
// rules table have AS OF the caller-supplied `asOf` instant — never
// Date.now() inside this module (asOf is a required DecisionTraceInput
// field, threaded through explicitly, exactly like Step 5A/5B/5C's own
// asOf parameters). See CommercialDecisionTrace.traceMode/evaluatedAsOf.
// If an organization rule has since been edited or superseded, or the
// Global Rulebook/AI guidance/activation registries have since changed,
// this trace reflects TODAY's versions/state, not necessarily what was
// true at the moment this field was originally confirmed. True historical
// replay ("why did Verdix interpret Contract X differently six months
// ago") would require persisting, AT DECISION TIME, at least: final value,
// final authority, Rulebook version, AI guidance version, activation
// version, organization rule ID/version, reviewer decision metadata, and a
// decision timestamp — a genuinely new persisted audit table. That is a
// future feature, deliberately not built here (item 11/3 — no persistence
// added merely because observability now exists); this module only ever
// reconstructs from what's already stored.
import type { FieldProvenance } from '@/lib/types'
import { isProvenanceResolved } from '@/lib/commercial-rule-status'
import { resolveVerdixRulebookShadow } from './resolver'
import { resolveVerdixRulebookActivation, VERDIX_RULEBOOK_ACTIVATION_VERSION } from './activation'
import { verdixCommercialRulebook } from './rules'
import { getRulebookAIGuidance, RULEBOOK_AI_GUIDANCE_VERSION } from './ai-guidance'
import { provenancedField } from './context'
import {
  matchOrganizationRules, type OrganizationRuleRecord, type OrganizationRuleMatchContext,
} from './organization-rules'
import { resolveOrganizationRulebookShadow } from './organization-rulebook-shadow'
import { isProductionActivatedOrganizationField, isOrganizationPolicyStale } from './organization-rulebook-production'
import type { ResolutionAuthority, ResolutionMethod } from './resolution'
import type { CommercialSemanticContext, RulebookFinding } from './types'
import type { RuleInterpretationContext } from './types'

// A Global/Organization Rulebook finding, unchanged — RulebookFinding
// already carries no raw contract text (see lib/rulebook/types.ts's own
// module comment); re-exported under the trace's own name per the spec so
// callers of this module don't need to reach into lib/rulebook/types.ts to
// know what a trace finding looks like.
export type DecisionTraceFinding = RulebookFinding

// Mirrors lib/rule-interpretation.ts's ProposalState by construction
// (structural copy, not an import) — decision-trace.ts is a Step 2-era
// pure domain module with no dependency on lib/rule-interpretation.ts
// today, and importing a type from there would create a reverse edge onto
// a file this module has no other reason to depend on. Kept in sync by
// hand; a mismatch would only ever be a type error at a future call site.
export type DecisionTraceProposalState = 'clear_from_source' | 'verdix_recommends' | 'decision_required'

export interface SourceStateTrace {
  // True only when the CURRENT provenance for this field is
  // 'contract_derived' — i.e. the source text itself is why this field is
  // (or was, before some other authority overrode it) resolved.
  explicitContractEvidence: boolean
  contractProvenance?: FieldProvenance | null
}

export interface AIGuidanceTrace {
  guidanceVersion: string
  // The EXACT deterministic guidance set selected for this interpretation
  // context (item 4) — computed by calling getRulebookAIGuidance(context)
  // directly, never inferred from the final proposal/output.
  guidanceRuleIds: string[]
  proposalState?: DecisionTraceProposalState
  // What the reviewer was shown at proposal time (RuleProposal.survival_
  // organization_policy's own struct) — rule id/version only, never the
  // policy's name/description/free text. Used solely to detect staleness
  // (organizationRulebook.staleAgainstSeenPolicy below), never to select a
  // rule — mirrors lib/rulebook/organization-rulebook-production.ts's own
  // isOrganizationPolicyStale contract exactly.
  seenOrganizationPolicy?: { ruleId: string; ruleVersion: number }
}

export interface GlobalRulebookTrace {
  rulebookVersion: string
  matchedRuleIds: string[]
  findings: DecisionTraceFinding[]
}

export type OrganizationRulebookTraceStatus = 'resolved' | 'unresolved' | 'conflict' | 'not_applicable'

export interface OrganizationRulebookTrace {
  // False when the organization matcher was never genuinely eligible to
  // apply — today, only when the field's CURRENT provenance is already
  // 'contract_derived' (item 6: never imply the organization policy
  // "competed and lost" when the contract already settled the question
  // outright) or the field isn't in the Step 5C production allowlist at
  // all. True otherwise, including when the field's current state is
  // reviewer_policy — an organization rule CAN genuinely match and be
  // outranked by a fresh reviewer decision (status stays 'not_applicable'
  // in that case too, but considered/matchedRuleIds show the real
  // competition happened, per the required Scenario C trace).
  considered: boolean
  // Every active, currently-matching organization rule for this field
  // (lib/rulebook/organization-rules.ts's matchOrganizationRules, reused
  // unmodified) — BEFORE any specificity narrowing resolveOrganizationRulebook
  // Shadow applies when picking a winner. Rule ids/versions only, never a
  // rule's name/description.
  matchedRuleIds: string[]
  selectedRuleId?: string
  selectedRuleVersion?: number
  status: OrganizationRulebookTraceStatus
  // True when a fresh resolution would otherwise apply, but differs from
  // what the AI proposal showed the reviewer (ai.seenOrganizationPolicy) —
  // lib/rulebook/organization-rulebook-production.ts's isOrganizationPolicyStale,
  // reused unmodified. When true, no organization authority is minted into
  // `final` regardless of what status would otherwise say (Scenario F).
  staleAgainstSeenPolicy?: boolean
}

export interface PrecedenceTrace {
  selectedAuthority?: ResolutionAuthority
  // Only authorities that GENUINELY entered resolution — never a
  // not-considered organization branch (item 7's "do not treat
  // not_applicable candidates as suppressed candidates").
  suppressedAuthorities: ResolutionAuthority[]
}

export interface ReviewerTrace {
  // True when the field's final state is currently governed by an
  // explicit reviewer decision (authority === 'reviewer_policy') —
  // reflects that the reviewer's decision is what stands today, not
  // necessarily that a decision was supplied in this exact operation
  // (this module derives from current persisted state, not a live request
  // — see this module's own header comment on historical replay).
  suppliedDecision: boolean
}

export interface ExecutionTrace {
  // Rulebook rule ids classified 'invariant' (lib/rulebook/rule-class.ts)
  // that matched this context at all — evaluated, not necessarily violated.
  invariantsEvaluated: string[]
  // The strict subset that are real, target:'execution' contradictions
  // (lib/rulebook/activation.ts's resolveVerdixRulebookActivation) —
  // NEVER a 'remains_unresolved' finding, and never a target:'promotion'
  // rule's finding either (item 8 — those stay in globalRulebook.findings,
  // enforced via a structurally separate mechanism, promotion-guard.ts,
  // not execution blocking).
  invariantViolations: string[]
  readinessBlocking: boolean
}

export interface CommercialDecisionTrace {
  // Step 8 amendment — explicit and permanent: this trace is always a
  // RECONSTRUCTION, computed now, from currently-persisted commercial
  // state + the Rulebook/Organization-Rulebook behavior available to the
  // running code as of evaluatedAsOf. It is not necessarily identical to
  // the decision environment that existed at the moment this field was
  // ORIGINALLY confirmed — an organization rule can be edited/superseded,
  // and the Global Rulebook/AI guidance/activation registries can change,
  // between then and whenever this trace is built. Only one value exists
  // today ('reconstructed_snapshot'); the type stays a union of one so a
  // future step that persists a real historical decision snapshot at
  // confirm-time can add 'persisted_historical' without a breaking change
  // to every existing consumer of this type.
  traceMode: 'reconstructed_snapshot'
  // Caller-supplied, never Date.now() inside this pure module (see
  // buildCommercialDecisionTrace) — the same instant used to evaluate
  // organization-rule temporal eligibility (DecisionTraceInput.asOf),
  // serialized so the trace is self-describing about when it was computed.
  evaluatedAsOf: string
  field: string
  // Present only when the field is actually resolved (some authority won).
  final?: { value: unknown; authority: ResolutionAuthority; method: ResolutionMethod }
  sourceState: SourceStateTrace
  ai?: AIGuidanceTrace
  globalRulebook: GlobalRulebookTrace
  organizationRulebook: OrganizationRulebookTrace
  precedence: PrecedenceTrace
  reviewer: ReviewerTrace
  execution: ExecutionTrace
  versions: { rulebook: string; activation: string; aiGuidance?: string }
}

// ── Generic composer ────────────────────────────────────────────────────

export interface DecisionTraceInput {
  field: string
  // The field's CURRENT persisted value/provenance — never "what a
  // request body claims", always what's actually stored (or would be,
  // for a not-yet-persisted resolution the caller is about to write).
  currentValue: unknown
  currentProvenance: FieldProvenance | null | undefined
  // Whether real contract source text backs `currentProvenance` — mirrors
  // lib/rulebook/types.ts's ProvenancedField.sourceTextPresent. Defaults to
  // `currentProvenance === 'contract_derived'` when omitted (the same
  // "these two are supposed to always agree" assumption ProvenancedField's
  // own doc comment describes) — pass an explicit value only when a more
  // authoritative per-field signal exists.
  sourceTextPresent?: boolean
  // The domain-specific slice(s) of CommercialSemanticContext this field
  // lives in (e.g. { creditApplication: ... } for a credit field) — never
  // includes provenancedFields; this composer builds that itself from
  // field/currentValue/currentProvenance/sourceTextPresent above, so a
  // caller can never accidentally pass raw text through that slot either.
  domainContext: Omit<CommercialSemanticContext, 'provenancedFields'>
  // AI layer — optional, structural facts only.
  interpretationContext?: RuleInterpretationContext
  aiProposalState?: DecisionTraceProposalState
  seenOrganizationPolicy?: { ruleId: string; ruleVersion: number; value: unknown }
  // Organization Rulebook — reuses Step 5A/5B primitives verbatim. Caller
  // loads organizationRules (a DB read) exactly like every existing
  // Organization Rulebook call site already does; this composer stays pure.
  organizationId: string
  organizationRules: OrganizationRuleRecord[]
  organizationMatchContext: OrganizationRuleMatchContext
  asOf: Date
}

interface OrganizationRulebookTraceResult {
  trace: OrganizationRulebookTrace
  // The winning candidate's value, present only when trace.status ===
  // 'resolved' and not stale — threaded to buildCommercialDecisionTrace's
  // `final` derivation so it never re-runs the shadow resolver a second
  // time for the same field/inputs (avoids any risk of the two disagreeing).
  candidateValue?: unknown
}

function organizationRulebookTrace(input: DecisionTraceInput): OrganizationRulebookTraceResult {
  if (!isProductionActivatedOrganizationField(input.field)) {
    return { trace: { considered: false, matchedRuleIds: [], status: 'not_applicable' } }
  }
  // Item 6 — a field the contract already, explicitly resolves was never
  // genuinely eligible for organization override; report it as such
  // rather than implying real competition that never happened.
  if (input.currentProvenance === 'contract_derived') {
    return { trace: { considered: false, matchedRuleIds: [], status: 'not_applicable' } }
  }

  const matched = matchOrganizationRules(
    input.organizationId,
    { context: input.organizationMatchContext, contractResolvedFields: new Set() },
    input.organizationRules,
    input.asOf,
  ).filter(r => r.targetField === input.field)

  // Authoritative status — reuses Step 5B's own precedence-aware resolver
  // (specificity narrowing + resolveFieldAuthority) rather than
  // re-deriving a winner here. current is threaded through so contract/
  // reviewer precedence is evaluated exactly as production does.
  const shadow = resolveOrganizationRulebookShadow({
    organizationId: input.organizationId,
    commercialContext: {
      current: { [input.field]: { value: input.currentValue, provenance: input.currentProvenance ?? null } },
      match: input.organizationMatchContext,
    },
    organizationRules: input.organizationRules,
    asOf: input.asOf,
  })
  const fieldResult = shadow.find(r => r.field === input.field)

  let base: OrganizationRulebookTrace
  let candidateValue: unknown
  if (!fieldResult || fieldResult.result === 'no_match') {
    base = { considered: true, matchedRuleIds: matched.map(r => r.id), status: 'unresolved' }
  } else if (fieldResult.result === 'candidate') {
    base = {
      considered: true, matchedRuleIds: matched.map(r => r.id), status: 'resolved',
      selectedRuleId: fieldResult.organizationCandidate!.ruleId,
      selectedRuleVersion: fieldResult.organizationCandidate!.ruleVersion,
    }
    candidateValue = fieldResult.organizationCandidate!.value
  } else if (fieldResult.result === 'conflict') {
    base = { considered: true, matchedRuleIds: matched.map(r => r.id), status: 'conflict' }
  } else {
    // 'precedence_blocked' — matched, but a higher-authority source (here,
    // only ever reviewer_policy — contract_derived was excluded above)
    // already governs this field. Still "not_applicable" to the FINAL
    // value, but considered/matchedRuleIds correctly show real competition.
    base = { considered: true, matchedRuleIds: matched.map(r => r.id), status: 'not_applicable' }
  }

  // Staleness (Scenario F) — only meaningful when the AI proposal showed
  // the reviewer a specific policy. Reuses isOrganizationPolicyStale
  // verbatim; when stale, the resolution computed above must never be
  // allowed to mint organization authority (enforced in `final` below).
  if (input.seenOrganizationPolicy) {
    const stale = isOrganizationPolicyStale(
      base.status === 'resolved'
        ? { status: 'resolved', value: candidateValue, ruleId: base.selectedRuleId, ruleVersion: base.selectedRuleVersion, reason: '' }
        : { status: base.status === 'conflict' ? 'conflict' : 'not_applicable', reason: '' },
      { ruleId: input.seenOrganizationPolicy.ruleId, ruleVersion: input.seenOrganizationPolicy.ruleVersion, value: input.seenOrganizationPolicy.value },
    )
    if (stale) return { trace: { ...base, staleAgainstSeenPolicy: true } }
  }
  return { trace: base, candidateValue: base.status === 'resolved' ? candidateValue : undefined }
}

// Item 3's worked example, generalized: authority is never derived from
// WHO helped interpret a value, only from WHOSE decision it is. Method
// captures the "how" — 'verdix_rulebook' when a semantic_interpretation
// rule affirmed this value in the SAME globalRulebook validation pass
// (never inferred from anything else), 'organization_rulebook' when
// that's the winning authority, 'existing_normalized_state' otherwise
// (the same default lib/rulebook/organization-rulebook-shadow.ts's own
// currentFieldCandidate uses for any already-persisted value, contract_
// derived or reviewer_policy alike).
//
// Deliberately does NOT filter findings by field-string equality against
// `field` — RulebookFinding.field addresses CommercialSemanticContext's
// OWN vocabulary (e.g. "creditApplication.carryForward"), a genuinely
// different dotted-path naming scheme from this module's `field`
// parameter (the Organization Rulebook's allowlisted vocabulary, e.g.
// "survival.carry_forward" — see lib/rulebook/organization-rules.ts's
// ORGANIZATION_RULEBOOK_ALLOWLISTED_FIELDS). Reconciling the two schemes
// isn't needed today: the current 9-rule registry has exactly ONE
// semantic_interpretation rule (credit.explicit_carry_forward_
// authoritative), so ruleClass + outcome alone is already unambiguous. If
// a second semantic_interpretation rule for a DIFFERENT field is ever
// added, this will need a real field-path reconciliation between the two
// vocabularies — flagged here rather than silently assumed correct forever.
function finalMethod(authority: ResolutionAuthority, findings: DecisionTraceFinding[]): ResolutionMethod {
  if (authority === 'organization_rulebook') return 'organization_rulebook'
  const semanticInterpretationSupport = findings.some(f =>
    f.outcome === 'supports' &&
    verdixCommercialRulebook.find(r => r.id === f.rule_id)?.ruleClass === 'semantic_interpretation',
  )
  return semanticInterpretationSupport ? 'verdix_rulebook' : 'existing_normalized_state'
}

export function buildCommercialDecisionTrace(input: DecisionTraceInput): CommercialDecisionTrace {
  const sourceTextPresent = input.sourceTextPresent ?? input.currentProvenance === 'contract_derived'
  const globalRulebookContext: CommercialSemanticContext = {
    ...input.domainContext,
    provenancedFields: [provenancedField(input.field, input.currentValue, input.currentProvenance, sourceTextPresent)],
  }

  const shadow = resolveVerdixRulebookShadow(globalRulebookContext)
  const globalRulebook: GlobalRulebookTrace = {
    rulebookVersion: shadow.rulebookVersion,
    matchedRuleIds: shadow.matchedRuleIds,
    findings: shadow.findings,
  }

  const activation = resolveVerdixRulebookActivation(globalRulebookContext)
  const invariantsEvaluated = shadow.matchedRuleIds.filter(id =>
    verdixCommercialRulebook.find(r => r.id === id)?.ruleClass === 'invariant',
  )
  const invariantViolations = activation.violations.filter(v => v.field === input.field).map(v => v.rule_id)

  const { trace: organizationRulebook, candidateValue: organizationCandidateValue } = organizationRulebookTrace(input)

  // final — the one authority that actually governs this field's value
  // today, or undefined when nothing has resolved it.
  let final: CommercialDecisionTrace['final']
  if (input.currentProvenance === 'contract_derived' || input.currentProvenance === 'reviewer_policy') {
    final = { value: input.currentValue, authority: input.currentProvenance, method: finalMethod(input.currentProvenance, globalRulebook.findings) }
  } else if (organizationRulebook.status === 'resolved' && !organizationRulebook.staleAgainstSeenPolicy) {
    final = { value: organizationCandidateValue, authority: 'organization_rulebook', method: 'organization_rulebook' }
  }
  // currentProvenance === 'verdix_recommends' (or null/undefined): never
  // resolves on its own (resolution.ts's own rule — a recommendation never
  // wins, regardless of rank) — final stays undefined.

  // precedence — derived from what's already computed above, never a
  // second, independent invocation of Step 4's resolver (avoids any risk
  // of the two disagreeing with each other).
  const suppressedAuthorities: ResolutionAuthority[] = []
  if (!final && input.currentProvenance === 'verdix_recommends') suppressedAuthorities.push('verdix_recommends')
  if (organizationRulebook.status === 'conflict') {
    suppressedAuthorities.push(...organizationRulebook.matchedRuleIds.map(() => 'organization_rulebook' as const))
  } else if (organizationRulebook.status === 'not_applicable' && organizationRulebook.considered && organizationRulebook.matchedRuleIds.length > 0) {
    suppressedAuthorities.push('organization_rulebook')
  } else if (organizationRulebook.staleAgainstSeenPolicy) {
    suppressedAuthorities.push('organization_rulebook')
  }
  const precedence: PrecedenceTrace = { selectedAuthority: final?.authority, suppressedAuthorities }

  const ai: AIGuidanceTrace | undefined = input.interpretationContext
    ? {
        guidanceVersion: RULEBOOK_AI_GUIDANCE_VERSION,
        guidanceRuleIds: getRulebookAIGuidance(input.interpretationContext).map(r => r.id),
        proposalState: input.aiProposalState,
        seenOrganizationPolicy: input.seenOrganizationPolicy
          ? { ruleId: input.seenOrganizationPolicy.ruleId, ruleVersion: input.seenOrganizationPolicy.ruleVersion }
          : undefined,
      }
    : undefined

  // readinessBlocking — final is only ever set with an authority
  // isProvenanceResolved already treats as resolved (contract_derived,
  // reviewer_policy, organization_rulebook — verdix_recommends/undefined
  // never populate `final`, by construction above), so this reduces to a
  // simple presence check; isProvenanceResolved is still called explicitly
  // (rather than just `!final`) so this stays visibly anchored to the one
  // canonical readiness gate instead of silently re-deriving its own rule.
  const readinessBlocking = !final || !isProvenanceResolved(final.authority as FieldProvenance)

  return {
    traceMode: 'reconstructed_snapshot',
    evaluatedAsOf: input.asOf.toISOString(),
    field: input.field,
    final,
    sourceState: {
      explicitContractEvidence: input.currentProvenance === 'contract_derived',
      contractProvenance: input.currentProvenance,
    },
    ai,
    globalRulebook,
    organizationRulebook,
    precedence,
    reviewer: { suppliedDecision: final?.authority === 'reviewer_policy' },
    execution: { invariantsEvaluated, invariantViolations, readinessBlocking },
    versions: {
      rulebook: globalRulebook.rulebookVersion,
      activation: VERDIX_RULEBOOK_ACTIVATION_VERSION,
      aiGuidance: ai ? RULEBOOK_AI_GUIDANCE_VERSION : undefined,
    },
  }
}
