'use client'

import Link from 'next/link'
import { useState, useEffect } from 'react'

interface Props {
  orgName: string
  orgId: string
}

function isAutoGeneratedName(name: string): boolean {
  // Auto-generated names come from email domain prefix: all lowercase, no spaces
  // e.g. "yahoo", "scalecraft", "gmail" — real names have spaces or mixed case
  return /^[a-z0-9]+$/.test(name)
}

export function OnboardingBanner({ orgName, orgId }: Props) {
  const [dismissed, setDismissed] = useState(true)

  useEffect(() => {
    const key = `onboarding-banner-dismissed-${orgId}`
    const isDismissed = localStorage.getItem(key) === '1'
    setDismissed(isDismissed)
  }, [orgId])

  const dismiss = () => {
    localStorage.setItem(`onboarding-banner-dismissed-${orgId}`, '1')
    setDismissed(true)
  }

  const needsSetup = isAutoGeneratedName(orgName)

  if (dismissed || !needsSetup) return null

  return (
    <div className="mx-4 md:mx-8 mt-4 md:mt-6 rounded-2xl border border-amber-200 bg-amber-50 px-5 py-4 flex items-start justify-between gap-4">
      <div className="flex items-start gap-3">
        <div className="w-8 h-8 rounded-full bg-amber-100 flex items-center justify-center flex-shrink-0 mt-0.5">
          <i className="ti ti-info-circle" style={{ fontSize: 16, color: '#92400E' }} />
        </div>
        <div>
          <p className="text-sm font-medium text-amber-900 mb-0.5">
            Your workspace was created automatically
          </p>
          <p className="text-sm text-amber-800 leading-relaxed">
            Your company name <span className="font-semibold">"{orgName}"</span> was generated from your email domain.
            Review your company details and invite your team before uploading contracts.
          </p>
          <div className="flex flex-wrap items-center gap-3 mt-3">
            <Link
              href="/setup"
              className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg transition-colors"
              style={{ background: '#92400E', color: '#fff' }}
            >
              <i className="ti ti-building" style={{ fontSize: 12 }} />
              Set up workspace
            </Link>
            <Link
              href="/settings/team"
              className="inline-flex items-center gap-1.5 text-xs font-medium px-3 py-1.5 rounded-lg border border-amber-300 text-amber-900 hover:bg-amber-100 transition-colors"
            >
              <i className="ti ti-users" style={{ fontSize: 12 }} />
              Invite team members
            </Link>
          </div>
        </div>
      </div>
      <button
        onClick={dismiss}
        className="flex-shrink-0 p-1 rounded-lg hover:bg-amber-100 transition-colors mt-0.5"
        aria-label="Dismiss"
      >
        <i className="ti ti-x" style={{ fontSize: 14, color: '#92400E' }} />
      </button>
    </div>
  )
}
