'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

interface OrgData {
  orgId: string
  orgName: string
  role: 'owner' | 'admin' | 'member'
  members: Array<{ user_email: string; role: string; status: string }>
}

function isAutoGeneratedName(name: string) {
  return /^[a-z0-9]+$/.test(name)
}

type BadgeType = 'existing' | 'optional' | 'required' | null

function StepBadge({ type }: { type: BadgeType }) {
  if (!type) return null
  if (type === 'existing') return (
    <span className="text-[11px] bg-stone/15 text-stone px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      Existing
    </span>
  )
  if (type === 'optional') return (
    <span className="text-[11px] border border-amber-400 text-amber-600 px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      New — optional
    </span>
  )
  if (type === 'required') return (
    <span className="text-[11px] border border-amber-400 text-amber-600 px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      Required
    </span>
  )
  return null
}

function TimelineStep({
  n, title, done, badge, active, isLast, onToggle, doneText, children,
}: {
  n: number
  title: string
  done: boolean
  badge?: BadgeType
  active: boolean
  isLast: boolean
  onToggle: () => void
  doneText: string
  children?: React.ReactNode
}) {
  const showBody = active

  return (
    <div className="flex gap-5">
      {/* Left column: circle + connector line */}
      <div className="flex flex-col items-center flex-shrink-0" style={{ width: 36 }}>
        <button
          onClick={onToggle}
          className={`w-9 h-9 rounded-full flex items-center justify-center transition-all flex-shrink-0 focus:outline-none ${
            done
              ? 'bg-forest shadow-sm'
              : 'bg-transparent border-2 border-amber-500 hover:border-amber-600'
          }`}
        >
          {done
            ? <i className="ti ti-check text-white" style={{ fontSize: 13 }} />
            : <span className="text-sm font-semibold text-amber-600">{n}</span>
          }
        </button>
        {!isLast && (
          <div className="flex-1 w-px bg-stone/20 mt-1" style={{ minHeight: 24 }} />
        )}
      </div>

      {/* Right column: title + content */}
      <div className={`flex-1 min-w-0 ${isLast ? 'pb-2' : 'pb-8'}`}>
        {/* Title row */}
        <button
          onClick={onToggle}
          className="flex items-center gap-2 mb-1 text-left w-full group"
        >
          <span className={`font-semibold text-sm leading-snug ${done ? 'text-stone' : 'text-ink'}`}>
            {title}
          </span>
          {badge && <StepBadge type={badge} />}
          {done && !showBody && (
            <i className="ti ti-pencil text-stone/30 group-hover:text-stone/60 transition-colors ml-auto flex-shrink-0" style={{ fontSize: 12 }} />
          )}
        </button>

        {/* Body */}
        {showBody ? (
          <div className="mt-3">
            {children}
          </div>
        ) : (
          <p className="text-sm text-stone/60">{doneText}</p>
        )}
      </div>
    </div>
  )
}

export default function SetupPage() {
  const router = useRouter()

  const [org, setOrg]               = useState<OrgData | null>(null)
  const [hasJobs, setHasJobs]       = useState(false)
  const [hasBilling, setHasBilling] = useState(false)
  const [loading, setLoading]       = useState(true)
  const [activeStep, setActive]     = useState<number | null>(null)

  const [orgName, setOrgName]         = useState('')
  const [savingOrg, setSavingOrg]     = useState(false)
  const [orgMsg, setOrgMsg]           = useState<{ ok: boolean; text: string } | null>(null)

  const [inviteEmail, setInviteEmail] = useState('')
  const [inviteRole, setInviteRole]   = useState<'member' | 'admin'>('member')
  const [inviting, setInviting]       = useState(false)
  const [inviteMsg, setInviteMsg]     = useState<{ ok: boolean; text: string } | null>(null)

  async function load() {
    const [orgRes, jobsRes, intRes] = await Promise.all([
      fetch('/api/org'),
      fetch('/api/jobs'),
      fetch('/api/org/integrations'),
    ])
    const orgData  = await orgRes.json()
    const jobsData = await jobsRes.json()
    const intData  = await intRes.json()

    if (orgData.orgId) {
      setOrg(orgData)
      setOrgName(orgData.orgName)
    }
    setHasJobs(Array.isArray(jobsData) && jobsData.length > 0)
    setHasBilling(
      Array.isArray(intData.integrations) &&
      intData.integrations.some((i: { connector_type: string; is_active: boolean }) =>
        i.connector_type === 'billing' && i.is_active
      )
    )
    setLoading(false)
  }

  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load() }, [])

  /* eslint-disable react-hooks/set-state-in-effect */
  useEffect(() => {
    if (!org) return
    const step1Done = !isAutoGeneratedName(org.orgName)
    const step2Done = org.members.length > 1
    const step3Done = hasJobs
    if (!step1Done) setActive(1)
    else if (!step2Done) setActive(2)
    else if (!step3Done) setActive(3)
    else if (!hasBilling) setActive(4)
    else setActive(null)
  }, [org, hasJobs, hasBilling])
  /* eslint-enable react-hooks/set-state-in-effect */

  async function saveOrgName(e: React.FormEvent) {
    e.preventDefault()
    if (!orgName.trim()) return
    setSavingOrg(true)
    setOrgMsg(null)
    const res = await fetch('/api/org', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: orgName.trim() }),
    })
    const data = await res.json()
    if (res.ok) {
      setOrgMsg({ ok: true, text: 'Workspace name updated.' })
      await load()
    } else {
      setOrgMsg({ ok: false, text: data.error ?? 'Failed to update.' })
    }
    setSavingOrg(false)
  }

  async function sendInvite(e: React.FormEvent) {
    e.preventDefault()
    setInviting(true)
    setInviteMsg(null)
    const res = await fetch('/api/org/invite', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: inviteEmail, role: inviteRole }),
    })
    const data = await res.json()
    if (res.ok) {
      setInviteMsg({ ok: true, text: `Invite sent to ${inviteEmail}` })
      setInviteEmail('')
      await load()
    } else {
      setInviteMsg({ ok: false, text: data.error ?? 'Failed to send invite.' })
    }
    setInviting(false)
  }

  function toggle(n: number) {
    setActive(prev => prev === n ? null : n)
  }

  if (loading) {
    return (
      <div className="p-8 flex items-center gap-2 text-stone text-sm">
        <i className="ti ti-loader-2 animate-spin" style={{ fontSize: 16 }} />
        Loading…
      </div>
    )
  }

  if (!org) return null

  const step1Done = !isAutoGeneratedName(org.orgName)
  const step2Done = org.members.length > 1
  const step3Done = hasJobs
  const step4Done = hasBilling
  const allDone   = step1Done && step2Done && step3Done
  const doneCount = [step1Done, step2Done, step3Done, step4Done].filter(Boolean).length
  const totalSteps = 4

  const canEdit = org.role === 'owner' || org.role === 'admin'

  const inputCls = "w-full text-sm border border-forest/20 rounded-xl px-4 py-2.5 bg-white text-ink placeholder:text-stone/50 focus:outline-none focus:ring-2 focus:ring-forest/20"
  const btnPrimary = "bg-forest text-white text-sm font-medium px-5 py-2.5 rounded-xl hover:bg-sage transition-colors disabled:opacity-50"

  return (
    <div className="p-4 md:p-8 max-w-2xl">

      {/* Header */}
      <div className="mb-10">
        <h1 className="font-display font-light text-ink text-2xl mb-1">Set up your workspace</h1>
        <p className="text-stone text-sm">
          {allDone
            ? 'Automate your billing workflows by connecting Verdix to your existing platforms.'
            : `${doneCount} of ${totalSteps} steps complete.`}
        </p>
        <div className="mt-4 h-1 bg-forest/8 rounded-full overflow-hidden max-w-xs">
          <div
            className="h-full bg-forest rounded-full transition-all duration-500"
            style={{ width: `${(doneCount / totalSteps) * 100}%` }}
          />
        </div>
      </div>

      {/* Timeline */}
      <div>

        <TimelineStep
          n={1}
          title="Name your workspace"
          done={step1Done}
          badge="existing"
          active={activeStep === 1}
          isLast={false}
          onToggle={() => toggle(1)}
          doneText={step1Done ? `"${org.orgName}" — no change needed.` : 'Give it your real company name.'}
        >
          <p className="text-sm text-stone mb-4">
            Your workspace name was generated from your email domain. Give it your real company
            name so your team knows where they are.
          </p>
          {canEdit ? (
            <form onSubmit={saveOrgName} className="flex flex-col gap-3">
              <input
                value={orgName}
                onChange={e => setOrgName(e.target.value)}
                className={inputCls}
                placeholder="Acme Corp"
                required
              />
              <div className="flex items-center gap-3">
                <button type="submit" disabled={savingOrg} className={btnPrimary}>
                  {savingOrg ? 'Saving…' : 'Save name'}
                </button>
                {orgMsg && (
                  <span className={`text-xs ${orgMsg.ok ? 'text-forest' : 'text-red-600'}`}>{orgMsg.text}</span>
                )}
              </div>
            </form>
          ) : (
            <p className="text-sm text-stone">Only owners and admins can change the workspace name.</p>
          )}
        </TimelineStep>

        <TimelineStep
          n={2}
          title="Invite your team"
          done={step2Done}
          badge="existing"
          active={activeStep === 2}
          isLast={false}
          onToggle={() => toggle(2)}
          doneText={step2Done ? `${org.members.length} members — no change needed.` : 'Add colleagues to review contracts.'}
        >
          <p className="text-sm text-stone mb-4">
            Add colleagues who will be reviewing contracts and approving billing configurations.
          </p>
          {canEdit ? (
            <form onSubmit={sendInvite} className="flex flex-col gap-3">
              <input
                type="email"
                placeholder="colleague@yourcompany.com"
                value={inviteEmail}
                onChange={e => setInviteEmail(e.target.value)}
                required
                className={inputCls}
              />
              <div className="flex items-center gap-3">
                <select
                  value={inviteRole}
                  onChange={e => setInviteRole(e.target.value as 'member' | 'admin')}
                  className="text-sm border border-forest/20 rounded-xl px-3 py-2.5 bg-white text-ink"
                >
                  <option value="member">Member — can view &amp; run jobs</option>
                  <option value="admin">Admin — can invite &amp; manage</option>
                </select>
                <button type="submit" disabled={inviting} className={btnPrimary}>
                  {inviting ? 'Sending…' : 'Invite'}
                </button>
              </div>
              {inviteMsg && (
                <p className={`text-xs ${inviteMsg.ok ? 'text-forest' : 'text-red-600'}`}>{inviteMsg.text}</p>
              )}
            </form>
          ) : (
            <p className="text-sm text-stone">Only owners and admins can invite team members.</p>
          )}
          {org.members.length > 1 && (
            <div className="mt-4 pt-4 border-t border-forest/8">
              <p className="text-[10px] font-semibold text-stone uppercase tracking-wider mb-2">Team so far</p>
              <div className="flex flex-col gap-1.5">
                {org.members.map(m => (
                  <div key={m.user_email} className="flex items-center justify-between text-sm">
                    <span className="text-ink">{m.user_email}</span>
                    <span className="text-[11px] text-stone capitalize">
                      {m.role}{m.status === 'invited' ? ' · invited' : ''}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}
          <Link href="/settings/team" className="inline-flex items-center gap-1 text-xs text-forest hover:underline mt-3">
            Manage full team →
          </Link>
        </TimelineStep>

        <TimelineStep
          n={3}
          title="Upload your first contract"
          done={step3Done}
          badge="existing"
          active={activeStep === 3}
          isLast={false}
          onToggle={() => toggle(3)}
          doneText="First contract uploaded — no change needed."
        >
          <p className="text-sm text-stone mb-4">
            Upload a customer contract as a PDF. Verdix extracts billing terms automatically —
            fees, overages, escalators, and payment schedule — ready for you to review.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link href="/configure/new" className={btnPrimary + ' inline-flex items-center gap-2'}>
              <i className="ti ti-upload" style={{ fontSize: 14 }} />
              Upload a contract
            </Link>
            <Link
              href="/verify/new"
              className="inline-flex items-center gap-2 text-sm font-medium px-5 py-2.5 rounded-xl border border-forest/20 text-forest hover:bg-cream transition-colors"
            >
              <i className="ti ti-file-check" style={{ fontSize: 14 }} />
              Run a billing audit
            </Link>
          </div>
          <p className="text-xs text-stone mt-3">
            <strong>Upload a contract</strong> to configure billing,
            or <strong>Run a billing audit</strong> to check an existing invoice.
          </p>
        </TimelineStep>

        <TimelineStep
          n={4}
          title="Connect a billing platform"
          done={step4Done}
          badge="optional"
          active={activeStep === 4}
          isLast={false}
          onToggle={() => toggle(4)}
          doneText="Billing platform connected — subscriptions will be pushed automatically."
        >
          <p className="text-sm text-stone mb-1">
            Admin picks their billing system and enters API credentials. Verdix pushes approved
            contracts as subscriptions directly to the platform. Without this step, billing push
            is disabled and users can only download a CSV.
          </p>
          <div className="mt-3 flex flex-col gap-1.5 text-sm text-stone">
            <p>
              <strong className="text-ink">Stripe:</strong>{' '}
              enter secret key → saved to org_integrations → replaces the hardwired dev key.
            </p>
            <p>
              <strong className="text-ink">Chargebee:</strong>{' '}
              enter site name + API key → same flow.
            </p>
            <p>
              <strong className="text-ink">Others:</strong>{' '}
              shown as &ldquo;coming soon&rdquo; with a one-click notification opt-in.
            </p>
          </div>
          <Link href="/settings/integrations" className={btnPrimary + ' inline-flex items-center gap-2 mt-4 text-xs px-4 py-2'}>
            <i className="ti ti-plug-connected" style={{ fontSize: 13 }} />
            Set up billing integration
          </Link>
        </TimelineStep>

        <TimelineStep
          n={5}
          title="Connect your CRM"
          done={false}
          badge="optional"
          active={activeStep === 5}
          isLast={true}
          onToggle={() => toggle(5)}
          doneText="CRM connected."
        >
          <p className="text-sm text-stone mb-1">
            Admin picks their CRM (HubSpot, Salesforce, Pipedrive, Attio) and connects via
            OAuth or API key.
          </p>
          <div className="mt-3 flex flex-col gap-1.5 text-sm text-stone">
            <p>
              <strong className="text-ink">Phase 1:</strong>{' '}
              HubSpot and Salesforce shown with &ldquo;Notify me when available&rdquo; — OAuth flows built in Phase 2.
            </p>
            <p>
              <strong className="text-ink">Phase 2:</strong>{' '}
              OAuth flow: after connecting, Verdix listens for Closed Won deal webhooks and
              auto-creates jobs. Optionally writes subscription ID back to deal.
            </p>
          </div>
          <Link href="/settings/integrations" className="inline-flex items-center gap-1 text-xs text-forest hover:underline mt-4">
            View CRM integrations →
          </Link>
        </TimelineStep>

      </div>

      {/* Footer */}
      <div className="mt-6 pt-6 border-t border-forest/8">
        <button
          onClick={() => router.push('/dashboard')}
          className="text-sm text-stone hover:text-ink transition-colors"
        >
          {allDone ? '← Back to dashboard' : 'Skip for now — go to dashboard →'}
        </button>
      </div>

    </div>
  )
}
