'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

// ── Types ─────────────────────────────────────────────────────────────────────

interface OrgData {
  orgId: string
  orgName: string
  role: 'owner' | 'admin' | 'member'
  members: Array<{ user_email: string; role: string; status: string }>
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function isAutoGeneratedName(name: string) {
  return /^[a-z0-9]+$/.test(name)
}

// ── Sub-components ────────────────────────────────────────────────────────────

function StepShell({
  n, title, done, active, onToggle, children,
}: {
  n: number
  title: string
  done: boolean
  active: boolean
  onToggle: () => void
  children: React.ReactNode
}) {
  return (
    <div className={`border rounded-2xl overflow-hidden transition-colors ${
      done ? 'border-forest/20 bg-white' : active ? 'border-forest/30 bg-white' : 'border-forest/10 bg-white'
    }`}>
      <button
        onClick={onToggle}
        className="w-full flex items-center gap-4 px-6 py-4 text-left hover:bg-cream/60 transition-colors"
      >
        {/* Circle / checkmark */}
        <div className={`w-7 h-7 rounded-full flex items-center justify-center flex-shrink-0 transition-colors ${
          done ? 'bg-forest' : active ? 'border-2 border-forest' : 'border-2 border-stone/30'
        }`}>
          {done
            ? <i className="ti ti-check text-white" style={{ fontSize: 13 }} />
            : <span className="text-xs font-semibold" style={{ color: active ? '#1A3D2B' : '#9CA3AF' }}>{n}</span>
          }
        </div>

        <div className="flex-1 min-w-0">
          <p className={`text-sm font-medium ${done ? 'text-stone line-through' : 'text-ink'}`}>{title}</p>
        </div>

        {done && <span className="text-[11px] text-forest font-medium flex-shrink-0">Done</span>}
        {!done && (
          <i
            className={`ti ${active ? 'ti-chevron-up' : 'ti-chevron-down'} text-stone/40 flex-shrink-0`}
            style={{ fontSize: 14 }}
          />
        )}
      </button>

      {active && !done && (
        <div className="px-6 pb-6 border-t border-forest/8">
          <div className="pt-4">{children}</div>
        </div>
      )}
    </div>
  )
}

// ── Main page ─────────────────────────────────────────────────────────────────

export default function SetupPage() {
  const router = useRouter()

  const [org, setOrg]           = useState<OrgData | null>(null)
  const [hasJobs, setHasJobs]   = useState(false)
  const [loading, setLoading]   = useState(true)
  const [activeStep, setActive] = useState<number | null>(null)

  // Step 1 state
  const [orgName, setOrgName]   = useState('')
  const [savingOrg, setSavingOrg] = useState(false)
  const [orgMsg, setOrgMsg]     = useState<{ ok: boolean; text: string } | null>(null)

  // Step 2 state
  const [inviteEmail, setInviteEmail]   = useState('')
  const [inviteRole, setInviteRole]     = useState<'member' | 'admin'>('member')
  const [inviting, setInviting]         = useState(false)
  const [inviteMsg, setInviteMsg]       = useState<{ ok: boolean; text: string } | null>(null)

  async function load() {
    const [orgRes, jobsRes] = await Promise.all([
      fetch('/api/org'),
      fetch('/api/jobs'),
    ])
    const orgData  = await orgRes.json()
    const jobsData = await jobsRes.json()

    if (orgData.orgId) {
      setOrg(orgData)
      setOrgName(orgData.orgName)
    }
    setHasJobs(Array.isArray(jobsData) && jobsData.length > 0)
    setLoading(false)
  }

  useEffect(() => { load() }, [])

  // Auto-open the first incomplete step
  useEffect(() => {
    if (!org) return
    const step1Done = !isAutoGeneratedName(org.orgName)
    const step2Done = org.members.some(m => m.status === 'invited' || m.status === 'active') && org.members.length > 1
    const step3Done = hasJobs

    if (!step1Done) setActive(1)
    else if (!step2Done) setActive(2)
    else if (!step3Done) setActive(3)
    else setActive(null)
  }, [org, hasJobs])

  async function saveOrgName(e: React.FormEvent) {
    e.preventDefault()
    if (!orgName.trim()) return
    setSavingOrg(true)
    setOrgMsg(null)
    const res = await fetch('/api/org', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: orgName.trim() }),
    })
    const data = await res.json()
    if (res.ok) {
      setOrgMsg({ ok: true, text: 'Workspace name updated.' })
      await load()
    } else {
      setOrgMsg({ ok: false, text: data.error ?? 'Failed to update.' })
    }
    setSavingOrg(false)
  }

  async function sendInvite(e: React.FormEvent) {
    e.preventDefault()
    setInviting(true)
    setInviteMsg(null)
    const res = await fetch('/api/org/invite', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ email: inviteEmail, role: inviteRole }),
    })
    const data = await res.json()
    if (res.ok) {
      setInviteMsg({ ok: true, text: `Invite sent to ${inviteEmail}` })
      setInviteEmail('')
      await load()
    } else {
      setInviteMsg({ ok: false, text: data.error ?? 'Failed to send invite.' })
    }
    setInviting(false)
  }

  function toggle(n: number) {
    setActive(prev => prev === n ? null : n)
  }

  if (loading) {
    return (
      <div className="p-8 flex items-center gap-2 text-stone text-sm">
        <i className="ti ti-loader-2 animate-spin" style={{ fontSize: 16 }} />
        Loading…
      </div>
    )
  }

  if (!org) return null

  const step1Done = !isAutoGeneratedName(org.orgName)
  const step2Done = org.members.length > 1
  const step3Done = hasJobs
  const allDone   = step1Done && step2Done && step3Done
  const doneCount = [step1Done, step2Done, step3Done].filter(Boolean).length

  const canEdit = org.role === 'owner' || org.role === 'admin'

  const inputCls = "w-full text-sm border border-forest/20 rounded-xl px-4 py-2.5 bg-white text-ink placeholder:text-stone/50 focus:outline-none focus:ring-2 focus:ring-forest/20"
  const btnPrimary = "bg-forest text-white text-sm font-medium px-5 py-2.5 rounded-xl hover:bg-sage transition-colors disabled:opacity-50"

  return (
    <div className="p-4 md:p-8 max-w-xl">

      {/* Header */}
      <div className="mb-8">
        <h1 className="font-display font-light text-ink text-2xl mb-1">Set up your workspace</h1>
        <p className="text-stone text-sm">
          {allDone
            ? 'Everything is configured. You\'re ready to go.'
            : `${doneCount} of 3 steps complete — takes about 5 minutes.`}
        </p>

        {/* Progress bar */}
        <div className="mt-4 h-1.5 bg-forest/8 rounded-full overflow-hidden">
          <div
            className="h-full bg-forest rounded-full transition-all duration-500"
            style={{ width: `${(doneCount / 3) * 100}%` }}
          />
        </div>
      </div>

      {/* All done state */}
      {allDone && (
        <div className="mb-6 rounded-2xl border border-forest/20 bg-forest/5 px-6 py-5 flex items-center gap-4">
          <div className="w-10 h-10 rounded-full bg-forest flex items-center justify-center flex-shrink-0">
            <i className="ti ti-check text-white" style={{ fontSize: 18 }} />
          </div>
          <div>
            <p className="text-sm font-medium text-ink">You're all set!</p>
            <p className="text-sm text-stone">Your workspace is ready. Head to the dashboard to get started.</p>
          </div>
        </div>
      )}

      {/* Steps */}
      <div className="flex flex-col gap-3 mb-6">

        {/* Step 1 — Name your workspace */}
        <StepShell
          n={1}
          title="Name your workspace"
          done={step1Done}
          active={activeStep === 1}
          onToggle={() => toggle(1)}
        >
          <p className="text-sm text-stone mb-4">
            Your workspace name was generated from your email domain. Give it your real company name so
            your team knows where they are.
          </p>
          {canEdit ? (
            <form onSubmit={saveOrgName} className="flex flex-col gap-3">
              <input
                value={orgName}
                onChange={e => setOrgName(e.target.value)}
                className={inputCls}
                placeholder="Acme Corp"
                required
              />
              <div className="flex items-center gap-3">
                <button type="submit" disabled={savingOrg} className={btnPrimary}>
                  {savingOrg ? 'Saving…' : 'Save name'}
                </button>
                {orgMsg && (
                  <span className={`text-xs ${orgMsg.ok ? 'text-forest' : 'text-red-600'}`}>{orgMsg.text}</span>
                )}
              </div>
            </form>
          ) : (
            <p className="text-sm text-stone">Only owners and admins can change the workspace name.</p>
          )}
        </StepShell>

        {/* Step 2 — Invite your team */}
        <StepShell
          n={2}
          title="Invite your team"
          done={step2Done}
          active={activeStep === 2}
          onToggle={() => toggle(2)}
        >
          <p className="text-sm text-stone mb-4">
            Add colleagues who will be reviewing contracts and approving billing configurations.
          </p>
          {canEdit ? (
            <form onSubmit={sendInvite} className="flex flex-col gap-3">
              <input
                type="email"
                placeholder="colleague@yourcompany.com"
                value={inviteEmail}
                onChange={e => setInviteEmail(e.target.value)}
                required
                className={inputCls}
              />
              <div className="flex items-center gap-3">
                <select
                  value={inviteRole}
                  onChange={e => setInviteRole(e.target.value as 'member' | 'admin')}
                  className="text-sm border border-forest/20 rounded-xl px-3 py-2.5 bg-white text-ink"
                >
                  <option value="member">Member — can view & run jobs</option>
                  <option value="admin">Admin — can invite & manage</option>
                </select>
                <button type="submit" disabled={inviting} className={btnPrimary}>
                  {inviting ? 'Sending…' : 'Invite'}
                </button>
              </div>
              {inviteMsg && (
                <p className={`text-xs ${inviteMsg.ok ? 'text-forest' : 'text-red-600'}`}>{inviteMsg.text}</p>
              )}
            </form>
          ) : (
            <p className="text-sm text-stone">Only owners and admins can invite team members.</p>
          )}

          {/* Show existing invites */}
          {org.members.length > 1 && (
            <div className="mt-4 pt-4 border-t border-forest/8">
              <p className="text-[10px] font-semibold text-stone uppercase tracking-wider mb-2">Team so far</p>
              <div className="flex flex-col gap-1.5">
                {org.members.map(m => (
                  <div key={m.user_email} className="flex items-center justify-between text-sm">
                    <span className="text-ink">{m.user_email}</span>
                    <span className="text-[11px] text-stone capitalize">
                      {m.role}{m.status === 'invited' ? ' · invited' : ''}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          )}

          <Link
            href="/settings/team"
            className="inline-flex items-center gap-1 text-xs text-forest hover:underline mt-3"
          >
            Manage full team →
          </Link>
        </StepShell>

        {/* Step 3 — Upload first contract */}
        <StepShell
          n={3}
          title="Upload your first contract"
          done={step3Done}
          active={activeStep === 3}
          onToggle={() => toggle(3)}
        >
          <p className="text-sm text-stone mb-4">
            Upload a customer contract as a PDF. Verdix will extract the billing terms automatically —
            fees, overages, escalators, and payment schedule — ready for you to review.
          </p>
          <div className="flex flex-wrap gap-3">
            <Link
              href="/configure/new"
              className={btnPrimary + ' inline-flex items-center gap-2'}
            >
              <i className="ti ti-upload" style={{ fontSize: 14 }} />
              Upload a contract
            </Link>
            <Link
              href="/verify/new"
              className="inline-flex items-center gap-2 text-sm font-medium px-5 py-2.5 rounded-xl border border-forest/20 text-forest hover:bg-cream transition-colors"
            >
              <i className="ti ti-file-check" style={{ fontSize: 14 }} />
              Run a billing audit
            </Link>
          </div>
          <p className="text-xs text-stone mt-3">
            Not sure where to start? <strong>Upload a contract</strong> to configure billing,
            or <strong>Run a billing audit</strong> to check an existing invoice.
          </p>
        </StepShell>

      </div>

      {/* Footer actions */}
      <div className="flex items-center gap-4">
        <button
          onClick={() => router.push('/dashboard')}
          className="text-sm text-stone hover:text-ink transition-colors"
        >
          {allDone ? '← Back to dashboard' : 'Skip for now → Dashboard'}
        </button>
      </div>

    </div>
  )
}
