'use client'

import { useEffect, useState } from 'react'
import Link from 'next/link'
import { useRouter } from 'next/navigation'

interface OrgData {
  orgId: string
  orgName: string
  role: 'owner' | 'admin' | 'member'
  members: Array<{ user_email: string; role: string; status: string }>
}

function isAutoGeneratedName(name: string) {
  return /^[a-z0-9]+$/.test(name)
}

type BadgeType = 'existing' | 'optional' | 'required' | null

function StepBadge({ type }: { type: BadgeType }) {
  if (!type) return null
  if (type === 'existing') return (
    <span className="text-[11px] bg-stone/15 text-stone px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      Existing
    </span>
  )
  if (type === 'optional') return (
    <span className="text-[11px] border border-amber-400 text-amber-600 px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      New — optional
    </span>
  )
  if (type === 'required') return (
    <span className="text-[11px] border border-amber-400 text-amber-600 px-2.5 py-0.5 rounded-full font-medium flex-shrink-0">
      Required
    </span>
  )
  return null
}

function StepCircle({ n, done, isLast }: { n: number; done: boolean; isLast: boolean }) {
  return (
    <div className="flex flex-col items-center flex-shrink-0" style={{ width: 36 }}>
      <div className={`w-9 h-9 rounded-full flex items-center justify-center flex-shrink-0 ${
        done ? 'bg-forest shadow-sm' : 'bg-transparent border-2 border-amber-500'
      }`}>
        {done
          ? <i className="ti ti-check text-white" style={{ fontSize: 13 }} />
          : <span className="text-sm font-semibold text-amber-600">{n}</span>
        }
      </div>
      {!isLast && <div className="flex-1 w-px bg-stone/20 mt-1" style={{ minHeight: 24 }} />}
    </div>
  )
}

// A step whose only purpose is to send the user to its own dedicated page —
// no inline form here, so the whole row is a real link, not an accordion.
function LinkStep({
  n, title, done, badge, note, href, doneText, todoText, isLast,
}: {
  n: number
  title: string
  done: boolean
  badge?: BadgeType
  note?: string
  href: string
  doneText: string
  todoText: string
  isLast: boolean
}) {
  return (
    <div className="flex gap-5">
      <StepCircle n={n} done={done} isLast={isLast} />
      <Link href={href} className={`flex-1 min-w-0 group ${isLast ? 'pb-2' : 'pb-8'}`}>
        <div className="flex items-center gap-2 mb-1">
          <span className={`font-semibold text-sm leading-snug transition-colors ${done ? 'text-stone' : 'text-ink'} group-hover:text-forest`}>
            {title}
          </span>
          {badge && <StepBadge type={badge} />}
          <i className="ti ti-arrow-right text-stone/30 group-hover:text-forest transition-colors ml-auto flex-shrink-0" style={{ fontSize: 13 }} />
        </div>
        {note && <p className="text-xs text-stone/50 mb-1">{note}</p>}
        <p className="text-sm text-stone/60">{done ? doneText : todoText}</p>
      </Link>
    </div>
  )
}

export default function SetupPage() {
  const router = useRouter()

  const [org, setOrg]               = useState<OrgData | null>(null)
  const [hasJobs, setHasJobs]       = useState(false)
  const [hasBilling, setHasBilling] = useState(false)
  const [hasMeters, setHasMeters]   = useState(false)
  const [loading, setLoading]       = useState(true)
  const [nameExpanded, setNameExpanded] = useState(false)

  const [orgName, setOrgName]         = useState('')
  const [savingOrg, setSavingOrg]     = useState(false)
  const [orgMsg, setOrgMsg]           = useState<{ ok: boolean; text: string } | null>(null)

  async function load() {
    const [orgRes, jobsRes, intRes, metersRes] = await Promise.all([
      fetch('/api/org'),
      fetch('/api/jobs'),
      fetch('/api/org/integrations'),
      fetch('/api/meters'),
    ])
    const orgData    = await orgRes.json()
    const jobsData    = await jobsRes.json()
    const intData     = await intRes.json()
    const metersData  = await metersRes.json().catch(() => null)

    if (orgData.orgId) {
      setOrg(orgData)
      setOrgName(orgData.orgName)
    }
    setHasJobs(Array.isArray(jobsData) && jobsData.length > 0)
    setHasBilling(
      Array.isArray(intData.integrations) &&
      intData.integrations.some((i: { connector_type: string; is_active: boolean }) =>
        i.connector_type === 'billing' && i.is_active
      )
    )
    setHasMeters(Array.isArray(metersData?.org_meters) && metersData.org_meters.length > 0)
    setLoading(false)
  }

  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load() }, [])

  useEffect(() => {
    if (!org) return
    // eslint-disable-next-line react-hooks/set-state-in-effect
    setNameExpanded(isAutoGeneratedName(org.orgName))
  }, [org])

  async function saveOrgName(e: React.FormEvent) {
    e.preventDefault()
    if (!orgName.trim()) return
    setSavingOrg(true)
    setOrgMsg(null)
    const res = await fetch('/api/org', {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ name: orgName.trim() }),
    })
    const data = await res.json()
    if (res.ok) {
      setOrgMsg({ ok: true, text: 'Workspace name updated.' })
      await load()
    } else {
      setOrgMsg({ ok: false, text: data.error ?? 'Failed to update.' })
    }
    setSavingOrg(false)
  }

  if (loading) {
    return (
      <div className="p-8 flex items-center gap-2 text-stone text-sm">
        <i className="ti ti-loader-2 animate-spin" style={{ fontSize: 16 }} />
        Loading…
      </div>
    )
  }

  if (!org) return null

  const step1Done       = !isAutoGeneratedName(org.orgName)
  const stepMetersDone  = hasMeters
  const stepPaymentDone = hasBilling
  const stepUploadDone  = hasJobs
  const stepTeamDone    = org.members.length > 1
  const allDone     = step1Done && stepMetersDone && stepPaymentDone && stepUploadDone && stepTeamDone
  const doneCount   = [step1Done, stepMetersDone, stepPaymentDone, stepUploadDone, stepTeamDone].filter(Boolean).length
  const totalSteps  = 5

  const canEdit = org.role === 'owner' || org.role === 'admin'

  const inputCls = "w-full text-sm border border-forest/20 rounded-xl px-4 py-2.5 bg-white text-ink placeholder:text-stone/50 focus:outline-none focus:ring-2 focus:ring-forest/20"
  const btnPrimary = "bg-forest text-white text-sm font-medium px-5 py-2.5 rounded-xl hover:bg-sage transition-colors disabled:opacity-50"

  return (
    <div className="p-4 md:p-8 max-w-2xl">

      {/* Header */}
      <div className="mb-10">
        <h1 className="font-display font-light text-ink text-2xl mb-1">Set up your workspace</h1>
        <p className="text-stone text-sm">
          {allDone
            ? 'Automate your billing workflows by connecting Verdix to your existing platforms.'
            : `${doneCount} of ${totalSteps} steps complete.`}
        </p>
        <div className="mt-4 h-1 bg-forest/8 rounded-full overflow-hidden max-w-xs">
          <div
            className="h-full bg-forest rounded-full transition-all duration-500"
            style={{ width: `${(doneCount / totalSteps) * 100}%` }}
          />
        </div>
      </div>

      {/* Timeline */}
      <div>

        {/* Step 1: Name your workspace — the one step with a real inline form,
            so it keeps its accordion (expand-to-edit) behavior. */}
        <div className="flex gap-5">
          <StepCircle n={1} done={step1Done} isLast={false} />
          <div className="flex-1 min-w-0 pb-8">
            <button
              onClick={() => setNameExpanded(v => !v)}
              className="flex items-center gap-2 mb-1 text-left w-full group"
            >
              <span className={`font-semibold text-sm leading-snug ${step1Done ? 'text-stone' : 'text-ink'}`}>
                Name your workspace
              </span>
              <StepBadge type="existing" />
              {step1Done && !nameExpanded && (
                <i className="ti ti-pencil text-stone/30 group-hover:text-stone/60 transition-colors ml-auto flex-shrink-0" style={{ fontSize: 12 }} />
              )}
            </button>
            {nameExpanded ? (
              <div className="mt-3">
                <p className="text-sm text-stone mb-4">
                  Your workspace name was generated from your email domain. Give it your real company
                  name so your team knows where they are.
                </p>
                {canEdit ? (
                  <form onSubmit={saveOrgName} className="flex flex-col gap-3">
                    <input
                      value={orgName}
                      onChange={e => setOrgName(e.target.value)}
                      className={inputCls}
                      placeholder="Acme Corp"
                      required
                    />
                    <div className="flex items-center gap-3">
                      <button type="submit" disabled={savingOrg} className={btnPrimary}>
                        {savingOrg ? 'Saving…' : 'Save name'}
                      </button>
                      {orgMsg && (
                        <span className={`text-xs ${orgMsg.ok ? 'text-forest' : 'text-red-600'}`}>{orgMsg.text}</span>
                      )}
                    </div>
                  </form>
                ) : (
                  <p className="text-sm text-stone">Only owners and admins can change the workspace name.</p>
                )}
              </div>
            ) : (
              <p className="text-sm text-stone/60">{step1Done ? `"${org.orgName}" — no change needed.` : 'Give it your real company name.'}</p>
            )}
          </div>
        </div>

        <LinkStep
          n={2}
          title="Set up your meters"
          note="For consumption-based agreements"
          badge="optional"
          done={stepMetersDone}
          href="/settings/meters"
          doneText="Meters configured."
          todoText="Register a usage meter if any of your agreements bill on consumption — skip this if all your billing is flat-fee."
          isLast={false}
        />

        <LinkStep
          n={3}
          title="Connect a payment system"
          badge="optional"
          done={stepPaymentDone}
          href="/settings/integrations"
          doneText="Payment system connected — approved contracts push automatically."
          todoText="Connect Stripe or Chargebee so approved contracts push as subscriptions automatically. Without this, billing push is disabled and users can only download a CSV."
          isLast={false}
        />

        <LinkStep
          n={4}
          title="Upload your first agreement"
          badge="existing"
          done={stepUploadDone}
          href="/configure/new"
          doneText="First agreement uploaded."
          todoText="Upload a signed contract as a PDF — Verdix extracts billing terms automatically: fees, overages, escalators, and payment schedule."
          isLast={false}
        />

        <LinkStep
          n={5}
          title="Manage team"
          badge="existing"
          done={stepTeamDone}
          href="/settings/team"
          doneText={`${org.members.length} members.`}
          todoText="Invite colleagues who will be reviewing contracts and approving billing configurations."
          isLast={true}
        />

      </div>

      {/* Footer */}
      <div className="mt-6 pt-6 border-t border-forest/8">
        <button
          onClick={() => router.push('/dashboard')}
          className="text-sm text-stone hover:text-ink transition-colors"
        >
          {allDone ? '← Back to dashboard' : 'Skip for now — go to dashboard →'}
        </button>
      </div>

    </div>
  )
}
